ALTER TYPE "ObservationRunStatus" ADD VALUE IF NOT EXISTS 'REVIEW_ONLY';

ALTER TABLE "ObservationRun"
  ADD COLUMN "candidateCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "autoAppliedCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0;
